# Generated by Django 3.0.4 on 2020-04-08 14:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200408_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_200_orig',
            field=models.TextField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='vk_token',
            field=models.CharField(default='token', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='badges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
