# Generated by Django 3.0.4 on 2020-04-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200408_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='city_title',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='favorites',
            new_name='favorite_users',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='groups',
            new_name='group_list',
        ),
    ]
