# Generated by Django 3.0.4 on 2020-04-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200408_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vk_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_token',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
