# Generated by Django 3.0.4 on 2020-04-10 19:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200410_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
